### ISSUE TITLE
on iOS 8.3 : `pbkdf2_hmac': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by Qwertylex** [hwaterke/ios_backup_extractor#1]
iOS version 8.3
backed up with https://github.com/libimobiledevice/libimobiledevice/blob/master/tools/idevicebackup2.c
[results in same output as iTunes, verified.]
Archlinux, tested with ruby 2.7.0 and 2.5.0

```
ios --veryverbose --extract ./extract/ --password [redacted] ./iphone5backup/fafba3c[redacted]
D, [2020-12-28T22:38:28.087647 #37565] DEBUG -- Retriever: Retrieving iDevice backup files in /home/alex/iphone5backup/fafba3c[redacted].
D, [2020-12-28T22:38:28.595081 #37565] DEBUG -- IosBackupExtractor::RawBackup4: Loading backup
I, [2020-12-28T22:38:29.085721 #37565]  INFO -- IosBackupExtractor::RawBackup4: Files in the original backup directory 24439
I, [2020-12-28T22:38:29.086340 #37565]  INFO -- IosBackupExtractor::RawBackup4: Encrypted backup
D, [2020-12-28T22:38:29.086678 #37565] DEBUG -- IosBackupExtractor::Keybag: Keybag of type Backup
Traceback (most recent call last):
        12: from /home/alex/.gem/ruby/2.7.0/bin/ios:23:in `<main>'
        11: from /home/alex/.gem/ruby/2.7.0/bin/ios:23:in `load'
        10: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/exe/ios:91:in `<top (required)>'
         9: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/exe/ios:91:in `each'
         8: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/exe/ios:99:in `block in <top (required)>'
         7: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/lib/ios_backup_extractor/raw_backup.rb:34:in `extract_to'
         6: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/lib/ios_backup_extractor/raw_backup4.rb:8:in `load!'
         5: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/lib/ios_backup_extractor/raw_backup.rb:91:in `load!'
         4: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/lib/ios_backup_extractor/keybag.rb:77:in `create_with_backup_manifest'
         3: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/lib/ios_backup_extractor/keybag.rb:39:in `unlock_backup_keybag_with_passcode'
         2: from /home/alex/.gem/ruby/2.7.0/gems/ios_backup_extractor-1.2.0/lib/ios_backup_extractor/keybag.rb:68:in `get_passcode_key_from_passcode'
         1: from /usr/lib/ruby/2.7.0/openssl/pkcs5.rb:14:in `pbkdf2_hmac'
/usr/lib/ruby/2.7.0/openssl/pkcs5.rb:14:in `pbkdf2_hmac': no implicit conversion of nil into String (TypeError)

```
I know your tool works with newer iOS versions (tested on 10.3.2) and same setup as above...
does it not support 8.3?

**Comment by hwaterke** [comment]
Hey @Qwertylex,

The tool should work for backups up to iOS 4!
The problem is located in the part that handles the encryption and I sadly do not have an encrypted backup from iOS 8 at hand. I might still have found the problem just from the code and released a new version of the gem. Hopefully it will work.
Let me know if it is fixed!

**Comment by Qwertylex** [comment]
Its fixed!
Works like magic!
Thanks :D 

```
ios --veryverbose --extract ./extract/ --password [redacted] ./fafba3c[redacted]
D, [2020-12-29T19:44:33.346756 #90222] DEBUG -- Retriever: Retrieving iDevice backup files in /home/alex/fafba3c[redacted].
D, [2020-12-29T19:44:33.874208 #90222] DEBUG -- IosBackupExtractor::RawBackup4: Loading backup
I, [2020-12-29T19:44:34.386789 #90222]  INFO -- IosBackupExtractor::RawBackup4: Files in the original backup directory 24439
I, [2020-12-29T19:44:34.386947 #90222]  INFO -- IosBackupExtractor::RawBackup4: Encrypted backup
D, [2020-12-29T19:44:34.387041 #90222] DEBUG -- IosBackupExtractor::Keybag: Keybag for backup of iOS 8.3
D, [2020-12-29T19:44:34.387101 #90222] DEBUG -- IosBackupExtractor::Keybag: Keybag of type Backup
D, [2020-12-29T19:44:37.827016 #90222] DEBUG -- Manifest Parser: 36,733 entries in the Manifest. Total size: 23.3 GB.
I, [2020-12-29T19:44:37.827654 #90222]  INFO -- IosBackupExtractor::RawBackup4: Starting backup extraction in directory /home/alex/extract/2020_12_27_iPhone52_iOS8.3_[redacted]_full
<snip>
D, [2020-12-29T19:59:33.100308 #90222] DEBUG -- IosBackupExtractor::RawBackup4: Extracting /home/alex/extract/2020_12_27_iPhone52_iOS8.3_[redacted]_full/HomeDomain/Library/Preferences/com.apple.powerlogd.plist
I, [2020-12-29T19:59:33.209887 #90222]  INFO -- IosBackupExtractor::RawBackup4: Keeping Status.plist in the backup.
I, [2020-12-29T19:59:33.346939 #90222]  INFO -- IosBackupExtractor::RawBackup4: Keeping Info.plist in the backup.
I, [2020-12-29T19:59:33.407306 #90222]  INFO -- IosBackupExtractor::RawBackup4: Keeping Manifest.plist in the backup.
I, [2020-12-29T19:59:33.808604 #90222]  INFO -- IosBackupExtractor::RawBackup4: Keeping Manifest.mbdb in the backup.
I, [2020-12-29T19:59:35.824926 #90222]  INFO -- IosBackupExtractor::RawBackup4: Backup extraction finished. 24439 files extracted.

```
